config/routes.rb
Thanxup::Application.routes.draw do
  devise_for :admins
  devise_for :owners
  resources :owner_approval, :only => [ :index ]
  scope :path => '/thanxup', :controller => :thanxup do
    get :home
    get :about
    get :contact
    get :unauthorized
    get :terms
    get :privacy
    get :subregion_options
  end
  resources :owners, :except => [ :index, :new, :create, :destroy ] do
    member do
      get :edit_payment
      put :update_payment
      delete :cancel_payment
      delete :remove_stripe_info
      put :enable_subscription
    end
    scope :path => '/admins', :controller => :admins do
      put :approve_owner, :as => :admin_approve_owner
    end
    resources :stores do
      resources :coupons
    end
    resources :campaigns, :except => [:show, :destroy] do
      member do
        delete :deactivate
      end
    end
  end
  root :to => 'thanxup#home'
end

app/controllers/thanxup_controller.rb
class ThanxupController < ApplicationController
  skip_authorization_check

  def home
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def terms
  end

  def unauthorized
  end

  def subregion_options
    render partial: '/layouts/subregion_select'
  end
end

app/helpers/thanxup_helper.rb
module ThanxupHelper
end

app/views/thanxup/_signed_in_home_admin.html.haml
.container
  You are signed in as an admin.

app/views/thanxup/_signed_in_home_owner.html.haml
.container
  .row-fluid
    .span12
      .hero-unit
        %h1 Thanxup
        %p This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
        %p
          %a.btn.btn-primary.btn-large
            Learn more &raquo;
      .row-fluid
        .span4
          %h2 Heading
          %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
          %p
            %a.btn
              View details &raquo;
        .span4
          %h2 Heading
          %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
          %p
            %a.btn
              View details &raquo;
        .span4
          %h2 Heading
          %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
          %p
            %a.btn
              View details &raquo;
      .row-fluid
        .span4
          %h2 Heading
          %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
          %p
            %a.btn
              View details &raquo;
        .span4
          %h2 Heading
          %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
          %p
            %a.btn
              View details &raquo;
        .span4
          %h2 Heading
          %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
          %p
            %a.btn
              View details &raquo;

app/views/thanxup/_signed_out_home.html.haml
- unless owner_signed_in? || admin_signed_in?
  #myCarousel.carousel.slide
    .carousel-inner
      .item.active
        %img{:src => "../assets/img/examples/slide-01.jpg", :alt => ""}
        .container
          .carousel-caption
            %h1 Incentivize
            %p.lead Give users more of a reason to visit your place of business with coupons, and allow them to reward you with social media exposure.
            %a.btn.btn-large.btn-primary{:href => new_owner_registration_path} Sign up today
      .item
        %img{:src => "../assets/img/examples/slide-02.jpg", :alt => ""}
        .container
          .carousel-caption
            %h1 Branch Out & Market
            %p.lead Quickly branch out through the massive tree of social media users by letting users do the marketing for you, through tweets and facebook posts.
            %a.btn.btn-large.btn-primary{:href => about_path} Learn more
      .item
        %img{:src => "../assets/img/examples/slide-02.jpg", :alt => ""}
        .container
          .carousel-caption
            %h1 Another example headline
            %p.lead Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
            %a.btn.btn-large.btn-primary{:href => "#"} Learn more
    %a.left.carousel-control{:href => "#myCarousel", "data-slide" => "prev"} &lsaquo;
    %a.right.carousel-control{:href => "#myCarousel", "data-slide" => "next"} &rsaquo;

  .container.marketing
    .row
      .span4
        %img{:class => "img-circle", :src => "http://placehold.it/140x140"}
        %h2 Heading
        %p Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
        %p
          %a{:class => "btn", :href => "#"}View details &raquo;
      .span4
        %img{:class => "img-circle", :src => "http://placehold.it/140x140"}
        %h2 Heading
        %p Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
        %p
          %a{:class => "btn", :href => "#"}View details &raquo;
      .span4
        %img{:class => "img-circle", :src => "http://placehold.it/140x140"}
        %h2 Heading
        %p Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
        %p
          %a{:class => "btn", :href => "#"}View details &raquo;

    %hr.featurette-divider

    .featurette
      %img.featurette-image.pull-right{:src => "../assets/img/examples/browser-icon-chrome.png"}
      %h2.featurette-heading
        First featurette headling.
        %span.muted It'll blow your mind.
      %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.

    %hr.featurette-divider

    .featurette
      %img.featurette-image.pull-right{:src => "../assets/img/examples/browser-icon-chrome.png"}
      %h2.featurette-heading
        First featurette headling.
        %span.muted It'll blow your mind.
      %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.

    %hr.featurette-divider

    .featurette
      %img.featurette-image.pull-right{:src => "../assets/img/examples/browser-icon-chrome.png"}
      %h2.featurette-heading
        First featurette headling.
        %span.muted It'll blow your mind.
      %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.

app/views/thanxup/about.html.haml
.container
  %h2 About Thanxup

app/views/thanxup/contact.html.haml
.container
  %h2 Contact

app/views/thanxup/home.html.haml
- if current_owner
  = render 'signed_in_home_owner'
- elsif current_admin
  = render 'signed_in_home_admin'
- else
  = render 'signed_out_home'

app/views/thanxup/unauthorized.html.haml
.container
  %h4 You are not authorized to view that page