config/routes.rb
Thanxup::Application.routes.draw do
  devise_for :admins
  devise_for :owners
  resources :owner_approval, :only => [ :index ]
  scope :path => '/thanxup', :controller => :thanxup do
    get :home
    get :about
    get :contact
    get :unauthorized
    get :terms
    get :privacy
    get :subregion_options
  end
  resources :owners, :except => [ :index, :new, :create, :destroy ] do
    member do
      get :edit_payment
      put :update_payment
      delete :cancel_payment
      delete :remove_stripe_info
      put :enable_subscription
    end
    scope :path => '/admins', :controller => :admins do
      put :approve_owner, :as => :admin_approve_owner
    end
    resources :stores do
      resources :coupons
    end
    resources :campaigns, :except => [:show, :destroy] do
      member do
        delete :deactivate
      end
    end
  end
  root :to => 'thanxup#home'
end

app/models/store.rb
class Store
  include Ripple::Document
  attr_accessor :country_code, :area_code, :number1, :number2, :extension
  before_validation :create_phone_number
  after_validation :check_if_exists

  DEFAULT_COUNTRY_CODE = '1'

  property :name,                 String, presence: true
  property :description,          String, presence: true
  property :city,                 String, presence: true
  property :state,                String, presence: true
  property :country,              String, presence: true
  property :address,              String, presence: true
  property :zip_code,             String, presence: true
  property :contact_email,        String, presence: true
  property :contact_phone_number, String, presence: true
  property :qr_code,              String
  property :type,                 String, presence: true
  property :owner_id,             String, index: true

  def owner
    Owner.find(owner_id.to_i)
  end

  def owner=(owner)
    self.owner_id = owner.id.to_s
  end

  def available_coupons
    Coupon.find_by_index('store_id', self.key)
  end

  def has_coupons?
    available_coupons.present?
  end

  private

  def create_phone_number
    self.country_code = self.country_code.blank? ? DEFAULT_COUNTRY_CODE : self.country_code
    self.contact_phone_number = Phoner::Phone.new(number: "#{self.number1}#{self.number2}",
                                                  area_code: "#{self.area_code}",
                                                  country_code: "#{self.country_code}",
                                                  extension: "#{self.extension}").format("+ %c (%a)-%f-%l %x")
    self.errors.add(:contact_phone_number, 'invalid phone number') and raise_error! unless Phoner::Phone.valid? self.contact_phone_number
  end

  def check_if_exists
    self.errors.add(:name, 'already exists') and raise_error! if Store.find_by_index('owner_id', self.owner_id).collect { |store| store.name }.include?(self.name)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :validate_stripe, :authorize
  rescue_from Ripple::DocumentInvalid, :with => :already_exists

  def index
    @stores = current_owner.stores
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(params[:store]) do |store|
      store.owner_id = current_owner.id
    end
    if @store.save!
      redirect_to owner_stores_path(owner_id: current_owner.id), notice: 'Successfully added a new store.'
    else
      render :new
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    if @store.update_attributes(params[:store])
      redirect_to owner_stores_path(owner_id: current_owner.id), notice: 'Successfully updated store.'
    else
      render :edit
    end
  end

  def destroy
    @store = Store.find(params[:id])
    @store.available_coupons.each { |coupon| coupon.destroy } if @store.available_coupons.present?
    @store.destroy
    redirect_to owner_stores_path(owner_id: current_owner.id), notice: 'Successfully removed store.'
  end

  protected

  def already_exists
    @store ||= Store.new
    if params[:action] == 'create'
      render :new
    else
      render :edit
    end
  end

  private

  def authorize
    authorize! :manage, Store
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.haml
= form_for [current_owner, @store] do |f|
  %div
    = popover(:store, :name)
    = f.text_field :name, placeholder: 'Store\'s Name'
  %div
    = popover(:store, :description)
    = f.text_area :description, placeholder: 'Description'
  %div
    = popover(:store, :country)
    = f.country_select :country, {:priority => %w(US ES CA), :prompt => 'Please select a country'}, {:class => 'country_select', :data => f.object.class.name.underscore.to_s}

  = render partial: '/layouts/subregion_select', locals: {parent_region: f.object.country, model: f.object.class.name.underscore.to_s}

  %div
    = popover(:store, :contact_email)
    = f.text_field :contact_email, placeholder: 'Email'
  %div
    = popover(:store, :contact_phone_number)
    = f.text_field :country_code, :maxlength => 5, :id => 'country_code', :placeholder => '+CC'
    #{"-"}
    = f.text_field :area_code, :maxlength => 3, :id => 'area_code', :placeholder => 'xxx'
    #{"-"}
    = f.text_field :number1, :maxlength => 3, :id => 'number1', :placeholder => 'xxx'
    #{"-"}
    = f.text_field :number2, :maxlength => 4, :id => 'number2', :placeholder => 'xxxx'
    #{"-"}
    = f.text_field :extension, :maxlength => 7, :id => 'extension', :placeholder => 'extension'
  %div
    = popover(:store, :type)
    = f.text_field :type, placeholder: 'Type of Business'
  %div
    = f.submit 'Save Store', class: 'btn'

app/views/stores/edit.html.haml
.container
  %h3 Edit store
  = render 'form'

app/views/stores/index.html.haml
.container
  - if @stores.present?
    %table.table.table-bordered
      %tr
        %th Name
        %th Address
        %th City
        %th State
        %th Zip Code
        %th Country
        %th Email
        %th Phone Number
        %th Type of Business
        %th &nbsp;
      - for store in @stores
        %tr
          %td= store.name
          %td= store.address
          %td= store.city
          %td= store.state
          %td= store.zip_code
          %td= store.country
          %td= store.contact_email
          %td= store.contact_phone_number
          %td= store.type
          %td
            .btn-group
              %button.btn Action
              %button.btn.dropdown-toggle{'data-toggle' => 'dropdown'}
                %span.caret
              %ul.dropdown-menu
                %li #{link_to 'Edit Store', edit_owner_store_path(owner_id: current_owner.id, id: store.key)}
                %li #{link_to 'Delete Store', owner_store_path(owner_id: current_owner.id, id: store.key), method: :delete, confirm: 'Are you sure?'}
                %li #{link_to 'View Coupons', owner_store_coupons_path(owner_id: current_owner.id, store_id: store.key)}
                %li #{link_to 'Add a Coupon', new_owner_store_coupon_path(owner_id: current_owner.id, store_id: store.key)}
  - else
    %h4 No stores have been created

app/views/stores/new.html.haml
.container
  %h3 Create a new store
  = render 'form'