config/routes.rb
Thanxup::Application.routes.draw do
  devise_for :admins
  devise_for :owners
  resources :owner_approval, :only => [ :index ]
  scope :path => '/thanxup', :controller => :thanxup do
    get :home
    get :about
    get :contact
    get :unauthorized
    get :terms
    get :privacy
    get :subregion_options
  end
  resources :owners, :except => [ :index, :new, :create, :destroy ] do
    member do
      get :edit_payment
      put :update_payment
      delete :cancel_payment
      delete :remove_stripe_info
      put :enable_subscription
    end
    scope :path => '/admins', :controller => :admins do
      put :approve_owner, :as => :admin_approve_owner
    end
    resources :stores do
      resources :coupons
    end
    resources :campaigns, :except => [:show, :destroy] do
      member do
        delete :deactivate
      end
    end
  end
  root :to => 'thanxup#home'
end

app/views/layouts/_messages.html.haml
- flash.each do |type, message|
  .alert.fade.in{ "data-alert" => "alert", :class => twitterized_type(type) }
    %a.close{href: "#", data: {dismiss: 'alert'}} &times;
    %h4= message

app/views/layouts/_subregion_select.html.haml
#wrapper
  - parent_region ||= params[:parent_region]
  - model ||= params[:model]
  - country = Carmen::Country.coded(parent_region)

  - if country.nil?
  - elsif country.subregions?
    = popover(model, :state)
    = subregion_select(model, :state, parent_region)
    %div
      = popover(model, :city)
      = text_field(model, :city, :placeholder => 'City')
    %div
      = popover(model, :address)
      = text_field(model, :address, :placeholder => 'Address')
    %div
      = popover(model, :zip_code)
      = text_field(model, :zip_code, :placeholder => 'Zip Code')
  - else
    = popover(model, :state)
    = text_field(model, :state)
    %div
      = popover(model, :city)
      = text_field(model, :city, :placeholder => 'City')
    %div
      = popover(model, :address)
      = text_field(model, :address, :placeholder => 'Address')
    %div
      = popover(model, :zip_code)
      = text_field(model, :zip_code, :placeholder => 'Zip Code')

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Thanxup
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "https://js.stripe.com/v1/", "application"
    = csrf_meta_tags
    = tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY

  %body
    .container.navbar-wrapper
      .navbar.navbar-inverse
        .navbar-inner
          = link_to 'Thanxup', root_path, :class => 'brand'
          .nav-collapse.collapse
            %ul.nav.pull-left
              - if current_owner && current_owner.customer_id.present?
                %li.dropdown
                  %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                    Stores
                    %span.caret
                  %ul.dropdown-menu{:role => 'menu', 'aria-labelleby' => 'dLabel'}
                    - if current_owner.stores.present?
                      %li #{link_to "View Your Stores", owner_stores_path(owner_id: current_owner.id)}
                      %li.divider
                    %li
                      = link_to 'Add New Store', new_owner_store_path(owner_id: current_owner.id)

                - if current_owner.stores.present?
                  %li.dropdown
                    %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                      Campaigns
                      %span.caret
                    %ul.dropdown-menu{:role => 'menu', 'aria-labelleby' => 'dLabel'}
                      - if current_owner.campaigns.present?
                        %li #{link_to "View Your Campaigns", owner_campaigns_path(owner_id: current_owner.id)}
                        %li.divider
                      %li
                        = link_to 'Add New Campaign', new_owner_campaign_path(owner_id: current_owner.id)
                - if current_owner.stores.present?
                  %li.dropdown
                    %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                      Coupons
                      %span.caret
                    %ul.dropdown-menu{:role => 'menu', 'aria-labelleby' => 'dLabel'}
                      - current_owner.stores.each do |store|
                        - if store.available_coupons.present?
                          %li #{link_to "View #{store.name}'s Coupons", owner_store_coupons_path(owner_id: current_owner.id, store_id: store.key)}
                        %li #{link_to "Add a Coupon to #{store.name}", new_owner_store_coupon_path(owner_id: current_owner.id, store_id: store.key)}
                        %li.divider
              - if current_owner
                %li.dropdown
                  %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                    Account
                    %span.caret
                  %ul.dropdown-menu{:role => 'menu', 'aria-labelleby' => 'dLabel'}
                    %li #{link_to "Add/Edit/Remove Credit Card", edit_payment_owner_path(id: current_owner.id)}
              %li
                = link_to 'About', about_path
              %li
                = link_to 'Contact', contact_path

            %ul.nav.pull-right
              - if current_owner
                %li
                  = link_to 'Logout', destroy_owner_session_path, method: :delete
                %li
                  - if current_owner.logo?
                    = link_to(image_tag(current_owner.logo.url(:avatar), :class => 'logo img-rounded'), owner_path(id: current_owner.id), :class => 'owner_image', :title => "#{current_owner.name}")
                  - else
                    = link_to(current_owner.name, owner_path(id: current_owner.id))
              - elsif current_admin
                %li
                  = link_to 'Owners', owner_approval_index_path
                %li
                  = link_to 'Logout', destroy_admin_session_path, method: :delete
              - else
                %li
                  = link_to 'Signup for Thanxup', new_owner_registration_path
                %li
                  = link_to 'Login', new_owner_session_path

  - if flash.present?
    .container
      =render :partial => "layouts/messages", :locals => {:flash => flash}

  = yield

  .container
    %hr.featurette-divider

    %footer
      %p.pull-right
        %a{:href => "#"} Back to top
      %p
        &copy; 2012 Thanxup, Inc. &middot;
        = link_to 'Privacy', privacy_path
        &middot;
        = link_to 'Terms', terms_path
        &middot;
        = link_to 'Admin', new_admin_session_path